### PR TITLE
Changed spiderweb chart to use opportunities as suggested

### PR DESCRIPTION
**Pull request by benedwards44**
The spiderweb chart is now using opportunities as suggested.

### CODE REVIEW

**Comment by wesnolte** [comment]
Champ, can you [reverse integrate](http://msdn.microsoft.com/en-us/library/vstudio/ee782536.aspx) what's there first please. Otherwise I get a merge conflict :)

**Comment by benedwards44** [comment]
Hmm I thought I did. I'll have another look.

**Comment by benedwards44** [comment]
I think there's 2 commits. One just had my changes, then the 2nd has your changes merged.

Can I remove a commit?

**Comment by wesnolte** [comment]
I made some major changes last night, and pushed them this afternoon. Just checked your repo and your missing some stuff e.g. renamed the VF page files. You should:
1. Create a branch for my code
2. Pull my changes into that branch
3. Merge that branch with your master branch

Let me know if I'm teaching you to suck eggs ;)

**Comment by benedwards44** [comment]
Oh yea I know what I've done now. I started to do that but missed some files. Stay tuned.

**Comment by wesnolte** [comment]
:+1:

**Comment by benedwards44** [comment]
Ok, latest changes merged. I think it should be alright now.

**Comment by wesnolte** [comment]
- [x] Be awesome.

**Pull request merged**
